INHERIT: ./docs/mkdocs_parent.yml
site_name: BetonQuest
site_author: BetonQuest Organisation
site_url: https://betonquest.org/
repo_name: BetonQuest on GitHub
repo_url: https://github.com/BetonQuest/BetonQuest
copyright: >
  <p id="bqCopyright">© 2014-{CurrentYear} BetonQuest Organisation. GPLv3</p>
  <a href="#__consent">Change cookie settings</a>

extra:
  version:
    provider: mike
    default:
      - RELEASE
      - DEV

  social:
    - icon: brands/discord
      link: https://discord.gg/rK6mfHq
    - icon: brands/opencollective
      link: https://opencollective.com/betonquest
    - icon: brands/hangar
      link: https://hangar.papermc.io/BetonQuest/BetonQuest
    - icon: brands/modrinth
      link: https://modrinth.com/plugin/betonquest
    - icon: brands/spigot
      link: https://spigotmc.org/resources/2117/
    - icon: fontawesome/brands/github
      link: https://github.com/BetonQuest/BetonQuest
    - icon: brands/mail
      link: mailto://contact@betonquest.org

extra_css:
  - '_webCode/css/coloredIcons.css'

#Notice that here are a few strange looking hairspaces in here.
#They make the space between the emojis and the text look equal
nav:
  - 'Home': index.md
  - 'Tutorials':
      - 'Overview': Tutorials/Overview.md
      - 'Getting Started':
          - 'About': Tutorials/Getting-Started/About.md
          - 'Setup Guide':
              - 'Setting up a Test Server': Tutorials/Getting-Started/Setup-Guide/Setting-up-a-Test-Server.md
              - 'Installing BetonQuest': Tutorials/Getting-Started/Setup-Guide/Installing-BetonQuest.md
              - 'Setting up VSCode': Tutorials/Getting-Started/Setup-Guide/Setting-up-VSCode.md
              - 'VSCode Basics': Tutorials/Getting-Started/Setup-Guide/VSCode-Basics.md
          - 'Basics':
              - 'YAML': Tutorials/Getting-Started/Basics/YAML-Basics.md
              - 'Conversations': Tutorials/Getting-Started/Basics/Conversations.md
              - 'Actions': Tutorials/Getting-Started/Basics/Actions.md
              - 'Objectives': Tutorials/Getting-Started/Basics/Objectives.md
              - 'Conditions': Tutorials/Getting-Started/Basics/Conditions.md
      - 'Features':
          - 'Tracking Quest Progress':
              - 'Overview': Tutorials/Features/Tracking-Quest-Progress/Overview.md
              - 'Tags': Tutorials/Features/Tracking-Quest-Progress/Tags.md
              - 'Points': Tutorials/Features/Tracking-Quest-Progress/Points.md
              - 'Stages': Tutorials/Features/Tracking-Quest-Progress/Stages.md
          - 'Schedules':
              - 'Overview': Tutorials/Features/Schedules/Overview.md
              - 'Daily Repetition': Tutorials/Features/Schedules/Daily-Repetition.md
              - 'Delayed Quest Steps': Tutorials/Features/Schedules/Delayed-Quest-Steps.md
              - 'Limited Time Events': Tutorials/Features/Schedules/Limited-Time-Events.md
      - 'Tools':
          - 'Handling YAML Errors': Tutorials/Tools/YAML-Errors.md
      - 'Syntax':
          - 'Quest Packages': Tutorials/Syntax/Quest-Packages.md
      - 'Quick Guides':
          - 'Quest Progress & State':
              - 'Displaying Progress': Tutorials/Quick-Guides/Quest-Progress-and-State/Displaying-Progress.md
              - 'Objectives in any Order': Tutorials/Quick-Guides/Quest-Progress-and-State/Objectives-in-any-order.md
          - 'Player UI & Feedback':
              - 'Using the Journal': Tutorials/Quick-Guides/Player-UI-and-Feedback/Using-the-Journal.md
              - 'Using Menus': Tutorials/Quick-Guides/Player-UI-and-Feedback/Using-Menus.md
              - 'Custom Notifications': Tutorials/Quick-Guides/Player-UI-and-Feedback/Custom-Notifications.md
              - 'Text Placeholders': Tutorials/Quick-Guides/Player-UI-and-Feedback/Text-Placeholders.md
          - 'Quest Flow & Lifecycle':
              - 'Quest Cancelers': Tutorials/Quick-Guides/Quest-Flow-and-Lifecycle/Using-Quest-Cancelers.md
              - 'Random Daily Quest': Tutorials/Quick-Guides/Quest-Flow-and-Lifecycle/Random-Daily-Quest.md
          - 'Rewards & Economy':
              - 'Rewarding Money': Tutorials/Quick-Guides/Rewards-and-Economy/Rewarding-Money.md
          - 'Items & Inventory':
              - 'Complex Quest Items': Tutorials/Quick-Guides/Items-and-Inventory/Complex-Quest-Items.md
          - 'Multiplayer & Global Quests':
              - 'Party Quests': Tutorials/Quick-Guides/Multiplayer-and-Global-Quests/Party-Quests.md
              - 'Global Daily Quests': Tutorials/Quick-Guides/Multiplayer-and-Global-Quests/Global-Random-Daily-Quests.md
              - 'Server Wide Quests': Tutorials/Quick-Guides/Multiplayer-and-Global-Quests/Server-Wide-Quests.md
          - 'World, NPCs & Visibility':
              - 'NPC Conversations': Tutorials/Quick-Guides/World-NPCs-and-Visibility/NPC-Conversations.md
              - 'NPC and Player Hider': Tutorials/Quick-Guides/World-NPCs-and-Visibility/NPC-and-Player-Hider.md
  - 'Documentation':
      - 'Overview': Documentation/Overview.md

      - 'Basics':
          - 'About Scripting': Documentation/Basics/About-Scripting.md
          - 'Scripting Elements': Documentation/Basics/Scripting-Elements.md
          - 'Packages & Templates': Documentation/Basics/Packages-&-Templates.md
          - 'Quoting & YAML': Documentation/Basics/Quoting-&-YAML.md

      - 'Advanced':
          - 'Conversations': Documentation/Advanced/Conversations.md
          - 'Text Formatting': Documentation/Advanced/Text-Formatting.md
          - 'Menus':
              - 'Documentation/Advanced/Menus/index.md'
              - 'Menu Example': Documentation/Advanced/Menus/Example.md
              - 'Elements': Documentation/Advanced/Menus/Elements.md
          - 'Journal': Documentation/Advanced/Journal.md
          - 'Quest Items': Documentation/Advanced/Items.md
          - 'Quest Cancelers': Documentation/Advanced/Quest-Cancelers.md
          - 'Player Hider': Documentation/Advanced/Player-Hider.md
          - 'Schedules': Documentation/Advanced/Schedules.md
          - 'Functions': Documentation/Advanced/Functions.md
          - 'Parties': Documentation/Advanced/Parties.md
          - "Notify IO's & Categories": Documentation/Advanced/Notification-IO's-&-Categories.md
          - 'Notification Settings': Documentation/Advanced/Notification-Settings.md

      - 'Reference':
          - 'Plugin Config': Documentation/Reference/Plugin-Config.md
          - 'Permissions & Commands': Documentation/Reference/Commands-and-Permissions.md
          - 'Actions List': Documentation/Reference/Actions-List.md
          - 'Objectives List': Documentation/Reference/Objectives-List.md
          - 'Conditions List': Documentation/Reference/Conditions-List.md
          - 'Placeholders List': Documentation/Reference/Placeholders-List.md
          - 'Integrations List':
              - 'Documentation/Reference/Integrations-List/index.md'
              - 'NPCs':
                  - 'Documentation/Reference/Integrations-List/NPCs/index.md'
                  - 'Citizens': Documentation/Reference/Integrations-List/NPCs/Citizens.md
                  - 'FancyNpcs': Documentation/Reference/Integrations-List/NPCs/FancyNpcs.md
                  - 'MythicMobs': Documentation/Reference/Integrations-List/NPCs/MythicMobs.md
                  - 'ZNPCsPlus': Documentation/Reference/Integrations-List/NPCs/ZNPCsPlus.md
              - 'Items':
                  - 'Documentation/Reference/Integrations-List/Items/index.md'
                  - 'Brewery & BreweryX': Documentation/Reference/Integrations-List/Items/Brewery.md
                  - 'CraftEngine': Documentation/Reference/Integrations-List/Items/CraftEngine.md
                  - 'ItemsAdder': Documentation/Reference/Integrations-List/Items/ItemsAdder.md
                  - 'Magic': Documentation/Reference/Integrations-List/Items/Magic.md
                  - 'MMOItems': Documentation/Reference/Integrations-List/Items/MMOItems.md
                  - 'MythicMobs': Documentation/Reference/Integrations-List/Items/MythicMobs.md
                  - 'Nexo': Documentation/Reference/Integrations-List/Items/Nexo.md
              - 'Holograms':
                  - 'Documentation/Reference/Integrations-List/Holograms/index.md'
                  - 'DecentHolograms': Documentation/Reference/Integrations-List/Holograms/DecentHolograms.md
                  - 'FancyHolograms': Documentation/Reference/Integrations-List/Holograms/FancyHolograms.md
                  - 'HolographicDisplays': Documentation/Reference/Integrations-List/Holograms/HolographicDisplays.md
              - 'Visuals':
                  - 'Documentation/Reference/Integrations-List/Visuals/index.md'
                  - 'EffectLib': Documentation/Reference/Integrations-List/Visuals/EffectLib.md
                  - 'FakeBlock': Documentation/Reference/Integrations-List/Visuals/FakeBlock.md
              - 'Scripting & Questing':
                  - 'Documentation/Reference/Integrations-List/Scripting-&-Questing/index.md'
                  - 'Denizen': Documentation/Reference/Integrations-List/Scripting-&-Questing/Denizen.md
                  - 'Quests': Documentation/Reference/Integrations-List/Scripting-&-Questing/Quests.md
                  - 'Skript': Documentation/Reference/Integrations-List/Scripting-&-Questing/Skript.md
              - 'Economy':
                  - 'Documentation/Reference/Integrations-List/Economy/index.md'
                  - 'JobsReborn': Documentation/Reference/Integrations-List/Economy/JobsReborn.md
                  - 'Shopkeepers': Documentation/Reference/Integrations-List/Economy/Shopkeepers.md
                  - 'Vault': Documentation/Reference/Integrations-List/Economy/Vault.md
              - 'MMO':
                  - 'Documentation/Reference/Integrations-List/MMO/index.md'
                  - 'AuraSkills': Documentation/Reference/Integrations-List/MMO/AuraSkills.md
                  - 'Fabled': Documentation/Reference/Integrations-List/MMO/Fabled.md
                  - 'Heroes': Documentation/Reference/Integrations-List/MMO/Heroes.md
                  - 'Magic': Documentation/Reference/Integrations-List/MMO/Magic.md
                  - 'mcMMO': Documentation/Reference/Integrations-List/MMO/McMMO.md
                  - 'MMOCore': Documentation/Reference/Integrations-List/MMO/MMOCore.md
                  - 'MMOLib': Documentation/Reference/Integrations-List/MMO/MMOLib.md
              - 'Administration':
                  - 'Documentation/Reference/Integrations-List/Administration/index.md'
                  - 'LuckPerms': Documentation/Reference/Integrations-List/Administration/LuckPerms.md
                  - 'PacketEvents': Documentation/Reference/Integrations-List/Administration/PacketEvents.md
                  - 'PlaceholderAPI': Documentation/Reference/Integrations-List/Administration/PlaceholderAPI.md
                  - 'RedisChat': Documentation/Reference/Integrations-List/Administration/RedisChat.md
                  - 'WorldEdit & FastAsyncWorldEdit': Documentation/Reference/Integrations-List/Administration/WorldEdit.md
                  - 'WorldGuard': Documentation/Reference/Integrations-List/Administration/WorldGuard.md
              - 'Miscellaneous':
                  - 'Documentation/Reference/Integrations-List/Miscellaneous/index.md'
                  - 'TrainCarts': Documentation/Reference/Integrations-List/Miscellaneous/TrainCarts.md
          - 'Font Config': Documentation/Reference/Font-Config.md
          - 'Definition Encyclopedia': Documentation/Reference/Definition-Encyclopedia.md

      - 'Updates':
          - 'Updating': Documentation/Updates/Updating.md
          - 'Migrations':
              - 'Migration 1.X to 2.X': Documentation/Updates/Migrations/Migration-1-2.md
              - 'Migration 2.X to 3.X': Documentation/Updates/Migrations/Migration-2-3.md
          - 'Changelog': Documentation/CHANGELOG.md

  - 'API':
      - 'Overview': API/Overview.md
      - 'Obtaining API': API/Obtaining-API.md
      - 'Concepts':
          - 'Overview': API/Concepts/Overview.md
          - 'Actions': API/Concepts/Actions.md
          - 'Objectives': API/Concepts/Objectives.md
          - 'Conditions': API/Concepts/Conditions.md
          - 'Placeholders': API/Concepts/Placeholders.md
          - 'NPCs': API/Concepts/NPCs.md
      - 'Integration':
          - 'Overview': API/Integration/Overview.md
          - 'Policies': API/Integration/Policies.md
          - 'Integration Builder': API/Integration/Integration-Builder.md
          - 'Implementation': API/Integration/Implementation.md
      - 'Tools':
          - 'Instruction': API/Tools/Instruction.md
          - 'Logging': API/Tools/Logging.md
          - 'Text Parsing': API/Tools/TextParsing.md
          - 'Profiles': API/Tools/Profiles.md
          - 'Versioning': API/Tools/Versioning.md
          - 'Configuration Accessor': API/Configuration-Files.md
          - 'Bukkit Configurations': API/BukkitConfigurations.md
          - 'Functions': API/Tools/Functions.md
      - 'Legacy':
          - 'Writing Implementations': API/Legacy/Writing-Implementations.md
          - 'Schedules': API/Legacy/Schedules.md
  - 'Participate':
      - 'Overview': Participate/Overview.md
      - 'Donate Money': Participate/Donating-Money.md
      - 'Setup Project': Participate/Setup-Project.md
      - Process:
          - 'Create a new Branch': Participate/Process/Create-a-new-Branch.md
          - 'Changing Docs':
              - 'Workflow': Participate/Process/Docs/Workflow.md
              - 'Fundamental Principles': Participate/Process/Docs/Principles.md
              - 'Guidelines': Participate/Process/Docs/Guidelines.md
              - 'Writing Tutorials': Participate/Process/Docs/Writing-Tutorials.md
              - 'mkdocs Customizations': Participate/Process/Docs/Customizations.md
              - 'Style Definitions': Participate/Process/Docs/Style-Definitions.md
          - 'Changing Code':
              - 'Workflow': Participate/Process/Code/Workflow.md
              - 'Checking Requirements': Participate/Process/Code/Checking-Requirements.md
              - 'Adding a Dependency': Participate/Process/Code/Adding-a-new-Dependency.md
              - 'Writing JUnit Tests': Participate/Process/Code/Writing-JUnit-Tests.md
          - 'Maintaining the Changelog': Participate/Process/Maintaining-the-Changelog.md
          - 'Submitting Changes': Participate/Process/Submitting-Changes.md
      - Misc:
          - 'Versioning & Releasing': Participate/Misc/Versioning-and-Releasing.md
  - 'Downloads': Downloads/index.md
