name: Setup Java and Maven
description: |
  This action setups Java and Maven and optionally caches the build artifacts.

inputs:
  JAVA_DISTRIBUTION:
    description: |
      The distribution of the JDK to use.
    required: false
    default: 'zulu'
  JAVA_OVERIDE:
    description: |
      The version of the JDK to use.
    required: false
  JAVA_CACHE:
    description: |
      The name of the Java cache to use.
    required: false
  JAVA_REPOSITORY_ID:
    description: |
      The id of the repository for authentication.
    required: false
    default: 'github'
  JAVA_REPOSITORY_USER:
    description: |
      The variable name for the username to use for the repository.
    required: false
    default: 'GITHUB_ACTOR'
  JAVA_REPOSITORY_PASS:
    description: |
      The variable name for the password to use for the repository.
    required: false
    default: 'GITHUB_TOKEN'
  MAVEN_TARGET_DIR:
    description: |
      The path to the artifacts target directory for caching.
    required: false

runs:
  using: composite
  steps:
    - name: Determine Java version
      uses: Wolf2323/java-version-export-github-action@main
      id: determine-java-version
      with:
        maven-expression: 'java.api.version'
    - name: Setup JDK ${{ steps.determine-java-version.outputs.java_major_version }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.JAVA_DISTRIBUTION }}
        java-version: ${{ inputs.JAVA_OVERIDE || steps.determine-java-version.outputs.java_major_version }}
        cache: ${{ inputs.JAVA_CACHE }}
        server-id: ${{ inputs.JAVA_REPOSITORY_ID }}
        server-username: ${{ inputs.JAVA_REPOSITORY_USER }}
        server-password: ${{ inputs.JAVA_REPOSITORY_PASS }}
    - uses: ./.github/actions/setup-java-maven/cache
      with:
        MAVEN_TARGET_DIR: ${{ inputs.MAVEN_TARGET_DIR }}
