name: BetonQuest
main: pl.betoncraft.betonquest.BetonQuest
description: Advanced quest plugin
authors: [Co0sh]
website: http://dev.bukkit.org/bukkit-plugins/betonquest/
softdepend: [Skript, Citizens, MythicMobs, Vault, Multiverse-Core, EffectLib, PlayerPoints, Heroes, Magic, Denizen, WorldEdit, WorldGuard, mcMMO, Shopkeepers, SkillAPI, Quests, PlaceholderAPI, HolographicDisplays, RacesAndClasses, LegendQuest]
version: 1.9-dev
commands:
  betonquest:
    description: General quest command
    usage: /<command>
    permission: betonquest.admin
    aliases: [q, bq, bquest, bquests, betonquests, quest, quests]
  journal:
    description: Adds journal to your inventory
    usage: /<command>
    permission: betonquest.journal
    aliases: [j, bj, bjournal, betonjournal, betonquestjournal]
  backpack:
    description: Opens quest backpack
    usage: /<command>
    permission: betonquest.backpack
    aliases: [b, bb, bbackpack, betonbackpack, betonquestbackpack]
  cancelquest:
    description: Opens the window with quest cancelers
    usage: /<command>
    permission: betonquest.backpack
    aliases: [bcq, bcancelquest, betoncancelquest, betonquestcancelquest]
  compass:
    description:
    usage: /<command>
    permission: betonquest.backpack
    aliases: [bc, bcompass, betoncompass, betonquestcompass]
  questlang:
    description: Changes the language
    usage: /<command> lang
    permission: betonquest.language
    aliases: [ql]
permissions:
  betonquest.admin:
    default: op
  betonquest.journal:
    default: true
  betonquest.backpack:
    default: true
  betonquest.conversation:
    default: true
  betonquest.language:
    default: true
  
