blank_issues_enabled: false
contact_links:
  - name: Share your ideas
    about: Share your ideas with us that aren't precise enough for a feature request yet!
    url: https://github.com/BetonQuest/BetonQuest/discussions/new?category=ideas
  - name: BetonQuest Support
    about: Quick, chat-based support for any usage questions on discord.
    url: https://discord.gg/rK6mfHq
