name: "Docs Feedback"
description: "Report unclear documentation."
body:
  - type: textarea
    attributes:
      label: "Docs version"
      description: "Please name the version of the docs that you use."
      placeholder: "2.0.0"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Improvement"
      description: "What can be improved?"
      render: Text
    validations:
      required: true
