name: "Docs Feedback"
title: "[Docs] "
description: "Report wrong or unclear documentation."
labels: [ "Documentation" ]
body:
  - type: input
    id: "version"
    attributes:
      label: "Docs Version"
      description: "The version of the documentation this report is about."
      placeholder: "3.0"
    validations:
      required: true

  - type: input
    id: "url"
    attributes:
      label: "Page URL"
      description: "The URL of the page this report is about."
      placeholder: "https://betonquest.org/RELEASE/"
    validations:
      required: true

  - type: textarea
    id: "description"
    attributes:
      label: "Improvement"
      description: "What can be improved?"
    validations:
      required: true

  - type: upload
    id: "screenshots"
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
    validations:
      required: false
