jdbcUrl=jdbc:mysql://localhost:3306/betonquest?useSSL=false
username=
password=
dataSource.cachePrepStmts=true
dataSource.prepStmtCacheSize=250
dataSource.prepStmtCacheSqlLimit=2048
dataSource.maxLifetime=1800000
dataSource.idleTimeout=600000
dataSource.connectionTimeout=30000
dataSource.poolName=BetonQuest-Pool
dataSource.maximumPoolSize=10
dataSource.minimumIdle=2
