# =====================================================================
#                BETONQUEST - DATABASE CONFIGURATION
# =====================================================================
jdbcUrl=jdbc:mysql://localhost:0000/betonquest?useSSL=false
password=
username=
# =====================================================================
#                      HIKARICP CONFIGURATION
# =====================================================================
# HikariCP is the system that manages connections to the database.
# NOTE: Don't change these settings unless you know what you're doing or are experiencing lag issues.
# =====================================================================
# Maximum time (in milliseconds) that the plugin will wait to obtain an available connection.
connectionTimeout=30000
# Maximum time (in milliseconds) that a connection can remain inactive before it is closed.
# (Default: 10 minutes)
idleTimeout=600000
# Maximum lifetime (in milliseconds) of a connection in the pool.
# (Default: 30 minutes)
maxLifetime=1800000
# Maximum number of simultaneous connections allowed to the database.
# TIP: Use this formula to calculate the recommended configuration for your server: (cores * 2) + hard drives.
maximumPoolSize=10
# Internal name that the connection group will have in the console.
poolName=BetonQuest-Pool
