name: Setup MkDocs Material
description: |
  This action sets up a Python environment with the latest version of
  MkDocs Material and its dependencies and optionally caches the build artifacts.

inputs:
  MKDOCS_MATERIAL_INSIDERS:
    description: |
      The GitHub token to use for installing the MkDocs Material Insiders.
    required: true
  MKDOCS_SITE_DIR:
    description: |
      The path to the MkDocs site directory for caching.
    required: false
  PYTHON_VERSION:
    description: |
      The version of Python to use.
    required: false
    default: '3.10'
  PYTHON_CACHE:
    description: |
      The name of the Python cache to use.
    required: false
  PYTHON_CACHE_DEPENDENCY_PATH:
    description: |
      The path to the Python cache dependency.
    required: false

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}
        cache: ${{ inputs.PYTHON_CACHE }}
        cache-dependency-path: ${{ inputs.PYTHON_CACHE_DEPENDENCY_PATH }}
    - uses: ./.github/actions/setup-mkdocs-material/cache
      with:
        MKDOCS_SITE_DIR: ${{ inputs.MKDOCS_SITE_DIR }}
    - name: Cache MkDocs site directory /.cache/plugins/optimize
      if: ${{ inputs.MKDOCS_SITE_DIR != '' }}
      uses: actions/cache@v4
      with:
        path: ${{ inputs.MKDOCS_SITE_DIR }}/.cache/plugins/optimize
        key: ${{ runner.os }}-hardcoded-media-cache
    - name: Install pngquant, a CI only dependency for mkdocs-material image optimization
      uses: awalsh128/cache-apt-pkgs-action@v1.2.2
      with:
        packages: pngquant
    - name: Update python pip
      id: setup-dependencies
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        python3 -m pip install --upgrade pip
    - name: Install dependencies with config/setup-docs-dependencies.py
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        python config/setup-docs-dependencies.py
      env:
        MKDOCS_MATERIAL_INSIDERS: ${{ inputs.MKDOCS_MATERIAL_INSIDERS }}
        MKDOCS_MATERIAL_INSIDERS_ENABLED: ${{ inputs.MKDOCS_MATERIAL_INSIDERS != '' }}
