package pl.betoncraft.betonquest.database;

public enum QueryType {
	
	SELECT_USED_OBJECTIVES,
	SELECT_UNUSED_OBJECTIVES,
	SELECT_USED_TAGS,
	SELECT_UNUSED_TAGS,
	SELECT_POINTS,
	SELECT_JOURNAL,
	
	SELECT_PLAYERS_TAGS,
	SELECT_PLAYERS_JOURNAL,
	SELECT_PLAYERS_POINTS,
	SELECT_PLAYERS_OBJECTIVES,
	
}
