package pl.betoncraft.betonquest.database;

public enum UpdateType {

	ADD_NEW_OBJECTIVE,
	DELETE_USED_OBJECTIVES,
	DELETE_POINTS,
	ADD_POINTS,
	DELETE_TAGS,
	ADD_TAGS,
	DELETE_JOURNAL,
	ADD_JOURNAL,
	
	DELETE_ALL_OBJECTIVES,
	
	UPDATE_OBJECTIVES,
	UPDATE_TAGS,

	UPDATE_PLAYERS_TAGS,
	UPDATE_PLAYERS_JOURNAL,
	UPDATE_PLAYERS_POINTS,
	UPDATE_PLAYERS_OBJECTIVES,
        
        DROP_OBJECTIVES, DROP_TAGS, DROP_POINTS, DROP_JOURNALS,
        INSERT_OBJECTIVE, INSERT_TAG, INSERT_POINT, INSERT_JOURNAL,
}
