name: Check if a new version is required by given paths
description: |
  Checks if changes are outside of the given paths. If this is the case, a new version is required.

inputs:
  TARGET_PATHS:
    description: |
      Multiline list of paths to check.
    required: true

outputs:
  NEW_VERSION_REQUIRED:
    description: |
      Whether a new version is required based on changes outside the target paths.
    value: ${{ steps.check_changes.outputs.new_version_required }}

runs:
  using: composite
  steps:
    - name: Check for changes
      id: check_changes
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        mapfile -t TARGET_PATHS_ARRAY <<< "${{ inputs.TARGET_PATHS }}"
        
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        NEW_VERSION_REQUIRED=false

        is_in_target_paths() {
          local file=$1
          for path in "${TARGET_PATHS_ARRAY[@]}"; do
            if [[ "$file" == "$path"/* || "$file" == "$path" ]]; then
              return 0
            fi
          done
          return 1
        }

        while IFS= read -r file; do
          if ! is_in_target_paths "$file"; then
            NEW_VERSION_REQUIRED=true
            break
          fi
        done <<< "$CHANGED_FILES"

        echo "NEW_VERSION_REQUIRED=$NEW_VERSION_REQUIRED" >> $GITHUB_ENV
        echo "new_version_required=$NEW_VERSION_REQUIRED" >> $GITHUB_OUTPUT
