name: Build
on:
  push:
    branches: [ "*" ]
    tags-ignore:
      - "v*-*"
  pull_request:

env:
  MODULES_TO_CHECK: "api lib"

jobs:
  prepare:
    name: Prepare Build Variables
    runs-on: ubuntu-latest

    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}
      VERSION_TYPE: ${{ steps.version.outputs.VERSION_TYPE }}
      VERSION_MAVEN: ${{ steps.version.outputs.VERSION_MAVEN }}
      VERSION_IS_NEW: ${{ steps.version.outputs.VERSION_IS_NEW }}
      SKIP_MODULES: ${{ steps.modules.outputs.SKIP_MODULES }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: BetonQuest/Workflows/.github/actions/version@main
        id: version
        with:
          ROOT_REPOSITORY: BetonQuest/BetonQuest
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXCLUDE_PATHS: |
            docs
            mkdocs.yml
          MAVEN_WRAPPER_DIR: '~/.m2/wrapper'
          SUB_MODULE: 'betonquest'
      - name: Determine modules to skip
        if: "steps.version.outputs.VERSION_TYPE == 'release'"
        id: modules
        shell: bash --noprofile --norc -euo pipefail {0}
        run: |
          read -ra modules <<< "$MODULES_TO_CHECK"
          skip_modules=()

          for module in "${modules[@]}"; do
            version=$(./mvnw --raw-streams help:evaluate -Dexpression=revision -q -DforceStdout --projects ":$module")
            tag="v${version}-${module}"
            if [ -n "$(git rev-parse -q --verify "refs/tags/$tag")" >/dev/null ] && [ "$(git rev-list -n1 "$tag")" != "$(git rev-parse HEAD)" ]; then
              echo "Deployment of module '"$module"' for tag '$tag' will bee skipped (tag already exists)"
              skip_modules+=("!:$module")
            else
              echo "Module '"$module"' for tag '$tag' will be deployed."
            fi
          done
          
          SKIP_MODULES=$(IFS=,; echo "${skip_modules[*]}")
          echo "SKIP_MODULES=$SKIP_MODULES" >> "$GITHUB_OUTPUT"

  build-code:
    name: Build Code
    needs: [ prepare ]
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ needs.prepare.outputs.VERSION }}
      VERSION_TYPE: ${{ needs.prepare.outputs.VERSION_TYPE }}
      VERSION_MAVEN: ${{ needs.prepare.outputs.VERSION_MAVEN }}
      VERSION_IS_NEW: ${{ needs.prepare.outputs.VERSION_IS_NEW }}
      SKIP_MODULES: ${{ needs.prepare.outputs.SKIP_MODULES }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
      - uses: BetonQuest/Workflows/.github/actions/setup-java-maven@main
        with:
          JAVA_CACHE: 'maven'
          MAVEN_BUILD_DIR: 'target/code'
          MAVEN_WRAPPER_DIR: '~/.m2/wrapper'
          JAVA_OVERRIDE: 25
      - uses: BetonQuest/Workflows/.github/actions/replace-code-variables@main
        with:
          VERSION: ${{ env.VERSION }}
          VERSION_TYPE: ${{ env.VERSION_TYPE }}
          VERSION_NAMESPACE: "plugin"
          SUB_MODULE: 'betonquest'
      - name: Build with Maven. Phase 'verify'
        shell: bash --noprofile --norc -euo pipefail {0}
        run: |
          if [ $VERSION_TYPE == 'release' ]; then CHANGELIST=-Dchangelist=; fi
          ./mvnw ${CHANGELIST-} -P Test-All -B verify
          mv target/code/BetonQuest.jar target/code/BetonQuest-${VERSION}.jar
          git diff > target/code/CodeChanges.patch
      - name: Upload Code
        uses: actions/upload-artifact@v7
        with:
          name: BetonQuest-Code
          path: |
            target/code/BetonQuest-${VERSION}.jar
            target/code/*/*.jar

  build-docs:
    name: Build Docs
    needs: [ prepare ]
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ needs.prepare.outputs.VERSION }}
      VERSION_TYPE: ${{ needs.prepare.outputs.VERSION_TYPE }}
      VERSION_MAVEN: ${{ needs.prepare.outputs.VERSION_MAVEN }}
      VERSION_IS_NEW: ${{ needs.prepare.outputs.VERSION_IS_NEW }}
      SKIP_MODULES: ${{ needs.prepare.outputs.SKIP_MODULES }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
        with:
          submodules: ${{ env.VERSION_TYPE == 'release' || env.VERSION_TYPE == 'development' }}
      - uses: BetonQuest/Workflows/.github/actions/setup-git-lfs@main
      - uses: BetonQuest/Workflows/.github/actions/setup-mkdocs-material@main
        with:
          MKDOCS_SITE_DIR: 'target/docs'
          PYTHON_CACHE: 'pip'
          PYTHON_CACHE_DEPENDENCY_PATH: 'docs/setup-docs-dependencies.py'
      - uses: ./.github/actions/replace-docs-variables
        with:
          VERSION: ${{ env.VERSION }}
          VERSION_TYPE: ${{ env.VERSION_TYPE }}
          VERSION_MAVEN: ${{ env.VERSION_MAVEN }}
          REPOSITORY_URL: ${{ vars.REPOSITORY_URL }}
      - name: Build with mkdocs
        shell: bash --noprofile --norc -euo pipefail {0}
        run: |
          mkdocs build --strict 
          git diff > target/docs/DocsChanges.patch
      - name: Upload Docs
        uses: actions/upload-artifact@v7
        with:
          name: BetonQuest-Docs
          path: |
            target/docs/
            !target/docs/DocsChanges.patch

  deploy-code:
    name: Deploy Code
    if: "needs.prepare.outputs.VERSION_TYPE == 'release' || needs.prepare.outputs.VERSION_TYPE == 'development' && needs.prepare.outputs.VERSION_IS_NEW == 'true'"
    needs: [ prepare, build-code, build-docs ]
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ needs.prepare.outputs.VERSION }}
      VERSION_TYPE: ${{ needs.prepare.outputs.VERSION_TYPE }}
      VERSION_MAVEN: ${{ needs.prepare.outputs.VERSION_MAVEN }}
      VERSION_IS_NEW: ${{ needs.prepare.outputs.VERSION_IS_NEW }}
      SKIP_MODULES: ${{ needs.prepare.outputs.SKIP_MODULES }}

    outputs:
      UPLOAD_PATH: ${{ steps.save_upload_path.outputs.upload_path }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
      - uses: BetonQuest/Workflows/.github/actions/setup-java-maven@main
        with:
          JAVA_CACHE: 'maven'
          JAVA_REPOSITORY_ID: 'betonquest'
          JAVA_REPOSITORY_USER: MAVEN_SERVER_USERNAME
          JAVA_REPOSITORY_PASS: MAVEN_SERVER_PASSWORD
          MAVEN_BUILD_DIR: 'target/code'
          MAVEN_WRAPPER_DIR: '~/.m2/wrapper'
          JAVA_OVERRIDE: 25
      - name: Load patch file
        shell: bash --noprofile --norc -euo pipefail {0}
        run: |
          git apply target/code/CodeChanges.patch
          rm target/code/CodeChanges.patch
      - name: Publish to Maven Repository
        shell: bash --noprofile --norc -euo pipefail {0}
        run: |
          if [ $VERSION_TYPE == 'release' ]; then CHANGELIST=-Dchangelist=; fi
          if [ -n "$SKIP_MODULES" ]; then PROJECTS="--projects $SKIP_MODULES"; fi
          ./mvnw ${CHANGELIST-} -P Skip-Verification,Test-None -B ${PROJECTS-} deploy | tee maven-deploy.log
        env:
          REPOSITORY_URL: ${{ vars.REPOSITORY_URL }}
          MAVEN_SERVER_USERNAME: ${{ secrets.MAVEN_SERVER_USERNAME }}
          MAVEN_SERVER_PASSWORD: ${{ secrets.MAVEN_SERVER_PASSWORD }}
      - name: Get upload URL from deploy log
        id: save_upload_path
        shell: bash --noprofile --norc -euo pipefail {0}
        run: |
          UPLOAD_PATH="$(grep -oP "(?<=Uploading to betonquest: $REPOSITORY_URL)org/betonquest/betonquest/.*/betonquest-.*-shaded.jar" maven-deploy.log)"
          echo "upload_path=$UPLOAD_PATH" >> "$GITHUB_OUTPUT"
        env:
          REPOSITORY_URL: ${{ vars.REPOSITORY_URL }}

  deploy-docs:
    name: Deploy Docs
    concurrency: gh-pages-deploy
    if: "needs.prepare.outputs.VERSION_TYPE == 'release' || needs.prepare.outputs.VERSION_TYPE == 'development'"
    needs: [ prepare, build-code, build-docs ]
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ needs.prepare.outputs.VERSION }}
      VERSION_TYPE: ${{ needs.prepare.outputs.VERSION_TYPE }}
      VERSION_MAVEN: ${{ needs.prepare.outputs.VERSION_MAVEN }}
      VERSION_IS_NEW: ${{ needs.prepare.outputs.VERSION_IS_NEW }}
      SKIP_MODULES: ${{ needs.prepare.outputs.SKIP_MODULES }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: ${{ env.VERSION_TYPE == 'release' }}
          token: ${{ secrets.ALL_REPOSITORIES_ACCESS_TOKEN }}
      - uses: BetonQuest/Workflows/.github/actions/setup-git-lfs@main
      - uses: BetonQuest/Workflows/.github/actions/setup-mkdocs-material@main
        with:
          MKDOCS_SITE_DIR: 'target/docs'
          PYTHON_CACHE: 'pip'
          PYTHON_CACHE_DEPENDENCY_PATH: 'docs/setup-docs-dependencies.py'
      - name: Load patch file
        shell: bash --noprofile --norc -euo pipefail {0}
        run: |
          git apply target/docs/DocsChanges.patch
          rm target/docs/DocsChanges.patch
      - name: Deploy to Github Pages
        if: "env.VERSION_TYPE == 'release' || env.VERSION_TYPE == 'development'"
        shell: bash --noprofile --norc -euo pipefail {0}
        run: |
          bash .github/scripts/docs_deployment.sh
        env:
          VERSION: ${{ env.VERSION }}
          VERSION_TYPE: ${{ env.VERSION_TYPE }}
          GIT_REF: ${{ github.ref }}
      - name: Set version Tag for Quest-Tutorials submodule
        if: "env.VERSION_TYPE == 'release'"
        shell: bash --noprofile --norc -euo pipefail {0}
        run: |
          git config --global user.name "BetonQuest-Bot"
          git config --global user.email "contact@betonquest.org"
          
          cd docs/_tutorials/
          git tag "v$VERSION"
          git push origin "v$VERSION"

  create-release:
    name: Create GitHub Release
    if: "needs.prepare.outputs.VERSION_TYPE == 'release'"
    needs: [ prepare, build-code, build-docs, deploy-code, deploy-docs ]
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ needs.prepare.outputs.VERSION }}
      VERSION_TYPE: ${{ needs.prepare.outputs.VERSION_TYPE }}
      VERSION_MAVEN: ${{ needs.prepare.outputs.VERSION_MAVEN }}
      VERSION_IS_NEW: ${{ needs.prepare.outputs.VERSION_IS_NEW }}
      SKIP_MODULES: ${{ needs.prepare.outputs.SKIP_MODULES }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
      - uses: BetonQuest/Workflows/.github/actions/setup-java-maven/cache@main
        with:
          MAVEN_BUILD_DIR: 'target/code'
      - uses: BetonQuest/Workflows/.github/actions/setup-mkdocs-material/cache@main
        with:
          MKDOCS_SITE_DIR: 'target/docs'
      - name: Zip Docs
        shell: bash --noprofile --norc -euo pipefail {0}
        run: |
          zip -r target/docs/Docs-${VERSION}.zip target/docs/
      - name: Set CHANGELOG.md version
        shell: bash --noprofile --norc -euo pipefail {0}
        run: |
          sed -i "s~## \[Unreleased\]~## \[${VERSION}\]~g" ./CHANGELOG.md
          DATE="$(date +%Y-%m-%d)"
          sed -i "s~\${maven\.build\.timestamp}~$DATE~g" ./CHANGELOG.md
      - name: Create release
        uses: docker://antonyurchenko/git-release:v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: false
          PRE_RELEASE: false
          CHANGELOG_FILE: CHANGELOG.md
          RELEASE_NAME: BetonQuest ${{ env.VERSION }}
        with:
          args: |
            target/code/BetonQuest-${VERSION}.jar
            target/docs/Docs-${VERSION}.zip

  publish-prepare:
    name: Publish Prepare
    if: "always() && !cancelled() && ( needs.prepare.outputs.VERSION_TYPE == 'release' || needs.prepare.outputs.VERSION_TYPE == 'development' && needs.prepare.outputs.VERSION_IS_NEW == 'true' )"
    needs: [ prepare, build-code, build-docs, deploy-code, deploy-docs, create-release ]
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ needs.prepare.outputs.VERSION }}
      VERSION_TYPE: ${{ needs.prepare.outputs.VERSION_TYPE }}
      VERSION_MAVEN: ${{ needs.prepare.outputs.VERSION_MAVEN }}
      VERSION_IS_NEW: ${{ needs.prepare.outputs.VERSION_IS_NEW }}
      SKIP_MODULES: ${{ needs.prepare.outputs.SKIP_MODULES }}

    outputs:
      PLUGIN_API_VERSION: ${{ steps.api_version.outputs.PLUGIN_API_VERSION }}
      COMMIT_DESCRIPTION: ${{ steps.commit_description.outputs.COMMIT_DESCRIPTION }}
      RELEASE_DESCRIPTION: ${{ steps.release_description.outputs.RELEASE_DESCRIPTION }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
      - uses: BetonQuest/Workflows/.github/actions/setup-java-maven/cache@main
        with:
          MAVEN_BUILD_DIR: 'target/code'
      - name: Prepare API version
        shell: bash --noprofile --norc -euo pipefail {0}
        id: api_version
        run: |
          PLUGIN_API_VERSION="$(./mvnw --raw-streams help:evaluate -Dexpression=plugin.api-version -DforceStdout -q --projects :betonquest)"
          echo "PLUGIN_API_VERSION=$PLUGIN_API_VERSION" >> "$GITHUB_OUTPUT"
      - name: Set Commit Description
        id: commit_description
        shell: bash --noprofile --norc -euo pipefail {0}
        run: |
          COMMIT_SUBJECT="$(git log -1 "$GITHUB_SHA" --pretty="%s")"
          COMMIT_MESSAGE="$(git log -1 "$GITHUB_SHA" --pretty="%b")"
          COMMIT_URL="https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA"
          COMMIT_DESCRIPTION="[__**${COMMIT_SUBJECT}**__](${COMMIT_URL})"
          if [[ -n "$COMMIT_MESSAGE" ]]; then
            COMMIT_DESCRIPTION="$COMMIT_DESCRIPTION"$'\n\n'"$COMMIT_MESSAGE"
          fi
          {
            echo 'COMMIT_DESCRIPTION<<EOF'
            printf '%s\n' "$COMMIT_DESCRIPTION"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
      - name: Get release
        uses: cardinalby/git-get-release-action@v1
        id: get_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: 'v${{ env.VERSION }}'
          doNotFailIfNotFound: true
      - name: Set release description
        id: release_description
        shell: bash --noprofile --norc -euo pipefail {0}
        run: |
          RELEASE_BODY="$RELEASE_BODY"
          if [[ -n "$RELEASE_BODY" ]]; then
            RELEASE_DESCRIPTION="$RELEASE_BODY"
          else
            RELEASE_DESCRIPTION="$COMMIT_DESCRIPTION"
          fi
          {
            echo 'RELEASE_DESCRIPTION<<EOF'
            printf '%s\n' "$RELEASE_DESCRIPTION"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
        env:
          RELEASE_BODY: ${{ steps.get_release.outputs.body }}
          COMMIT_DESCRIPTION: ${{ steps.commit_description.outputs.COMMIT_DESCRIPTION }}

  discord-publish:
    name: Discord Publish
    if: "always() && !cancelled() && ( needs.prepare.outputs.VERSION_TYPE == 'release' || needs.prepare.outputs.VERSION_TYPE == 'development' && ( needs.prepare.outputs.VERSION_IS_NEW == 'true' || failure() ) )"
    needs: [ prepare, build-code, build-docs, deploy-code, deploy-docs, create-release, publish-prepare ]
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ needs.prepare.outputs.VERSION }}
      VERSION_TYPE: ${{ needs.prepare.outputs.VERSION_TYPE }}
      VERSION_MAVEN: ${{ needs.prepare.outputs.VERSION_MAVEN }}
      VERSION_IS_NEW: ${{ needs.prepare.outputs.VERSION_IS_NEW }}
      SKIP_MODULES: ${{ needs.prepare.outputs.SKIP_MODULES }}
      UPLOAD_PATH: ${{ needs.deploy-code.outputs.UPLOAD_PATH }}
      COMMIT_DESCRIPTION: ${{ needs.publish-prepare.outputs.COMMIT_DESCRIPTION }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
      - name: Determine job state
        if: always() && !cancelled()
        shell: bash --noprofile --norc -euo pipefail {0}
        run: |
          if [[ "$PREPARE" == "failure" || "$BUILD_CODE" == "failure" || "$BUILD_DOCS" == "failure" || "$DEPLOY_CODE" == "failure" || "$DEPLOY_DOCS" == "failure" || "$CREATE_RELEASE" == "failure" || "$PUBLISH_PREPARE" == "failure" ]]; then
            echo "JOB_STATUS=failure" >> "$GITHUB_ENV"
          else
            echo "JOB_STATUS=success" >> "$GITHUB_ENV"
          fi
        env:
          PREPARE: ${{ needs.prepare.result }}
          BUILD_CODE: ${{ needs.build-code.result }}
          BUILD_DOCS: §{{ needs.build-docs.result }}
          DEPLOY_CODE: ${{ needs.deploy-code.result }}
          DEPLOY_DOCS: ${{ needs.deploy-docs.result }}
          CREATE_RELEASE: ${{ needs.create-release.result }}
          PUBLISH_PREPARE: ${{ needs.publish-prepare.result }}
      - name: Publish to Discord
        if: "always() && !cancelled()"
        shell: bash --noprofile --norc -euo pipefail {0}
        run: |
          bash .github/scripts/discord_notification.sh
        env:
          JOB_STATUS: ${{ env.JOB_STATUS }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          DOCS_URL: ${{ vars.DOCS_URL }}
          UPLOAD_PATH: ${{ env.UPLOAD_PATH }}
          COMMIT_DESCRIPTION: ${{ env.COMMIT_DESCRIPTION }}

  hangar-publish:
    name: Hangar Publish
    if: "always() && !cancelled() && !failure() && ( needs.prepare.outputs.VERSION_TYPE == 'release' || needs.prepare.outputs.VERSION_TYPE == 'development' && needs.prepare.outputs.VERSION_IS_NEW == 'true' )"
    needs: [ prepare, build-code, build-docs, deploy-code, deploy-docs, create-release, publish-prepare ]
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ needs.prepare.outputs.VERSION }}
      VERSION_TYPE: ${{ needs.prepare.outputs.VERSION_TYPE }}
      VERSION_MAVEN: ${{ needs.prepare.outputs.VERSION_MAVEN }}
      VERSION_IS_NEW: ${{ needs.prepare.outputs.VERSION_IS_NEW }}
      SKIP_MODULES: ${{ needs.prepare.outputs.SKIP_MODULES }}
      PLUGIN_API_VERSION: ${{ needs.publish-prepare.outputs.PLUGIN_API_VERSION }}
      RELEASE_DESCRIPTION: ${{ needs.publish-prepare.outputs.RELEASE_DESCRIPTION }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
      - uses: BetonQuest/Workflows/.github/actions/setup-java-maven/cache@main
        with:
          MAVEN_BUILD_DIR: 'target/code'
      - name: Publish to Hangar
        uses: milkdrinkers/Hangar-Publish@v2
        with:
          api_token: ${{ secrets.HANGAR_TOKEN }}
          slug: ${{ github.event.repository.name }}
          version: ${{ env.VERSION }}
          channel: ${{ env.VERSION_TYPE }}
          description: ${{ env.RELEASE_DESCRIPTION }}
          files: |
            [
              {
                "path": "target/code/BetonQuest-${{ env.VERSION }}.jar",
                "platforms": ["PAPER"]
              }
            ]
          platform_dependencies: |
            {
              "PAPER": [">=${{ env.PLUGIN_API_VERSION }}"]
            }

  modrinth-publish:
    name: Modrinth Publish
    if: "always() && !cancelled() && !failure() && ( needs.prepare.outputs.VERSION_TYPE == 'release' || needs.prepare.outputs.VERSION_TYPE == 'development' && needs.prepare.outputs.VERSION_IS_NEW == 'true' )"
    needs: [ prepare, build-code, build-docs, deploy-code, deploy-docs, create-release, publish-prepare ]
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ needs.prepare.outputs.VERSION }}
      VERSION_TYPE: ${{ needs.prepare.outputs.VERSION_TYPE }}
      VERSION_MAVEN: ${{ needs.prepare.outputs.VERSION_MAVEN }}
      VERSION_IS_NEW: ${{ needs.prepare.outputs.VERSION_IS_NEW }}
      SKIP_MODULES: ${{ needs.prepare.outputs.SKIP_MODULES }}
      PLUGIN_API_VERSION: ${{ needs.publish-prepare.outputs.PLUGIN_API_VERSION }}
      RELEASE_DESCRIPTION: ${{ needs.publish-prepare.outputs.RELEASE_DESCRIPTION }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
      - uses: BetonQuest/Workflows/.github/actions/setup-java-maven/cache@main
        with:
          MAVEN_BUILD_DIR: 'target/code'
      - name: Determine version channel
        shell: bash --noprofile --norc -euo pipefail {0}
        run: |
          if [[ "$VERSION_TYPE" == "release" ]]; then
            echo "MODRINTH_VERSION_TYPE=release" >> "$GITHUB_ENV"
          else
            echo "MODRINTH_VERSION_TYPE=beta" >> "$GITHUB_ENV"
          fi
      - name: Publish to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          name: '${{ github.event.repository.name }} ${{ env.VERSION }}'
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: 'uVhukxY9'
          version: ${{ env.VERSION }}
          channel: ${{ env.MODRINTH_VERSION_TYPE }}
          loaders: 'paper'
          changelog: ${{ env.RELEASE_DESCRIPTION }}
          files: 'target/code/BetonQuest-${{ env.VERSION }}.jar'
          game-versions: ">=${{ env.PLUGIN_API_VERSION }}"
